name: Ruby

on: [pull_request, push]

jobs:

  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
  
      - name: Create database
        env:
          RAILS_ENV: "test"
          DB_USER: postgres
          DB_PASSWORD: postgres
          DATABASE_URL: "postgres://postgres@localhost:5432/proyecto-Testing_test"
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Run tests
        env:
          RAILS_ENV: "test"
          DB_USER: postgres
          DB_PASSWORD: postgres
          DATABASE_URL: "postgres://postgres@localhost:5432/proyecto-Testing_test"
        run: bundle exec rails test

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0

        # https://medium.com/@_ClementF/rails-cypress-running-on-github-actions-d73ead9335cd
        start: bundle exec rails server -e test -p 5002
        # quote the url to be safe against YML parsing surprises
        wait-on: 'http://localhost:5002'
        browser: chrome
        headless: trued
            start: npm start

 
      
